In [41]:
import pandas as pd

import json

### Choose a time partition

In [42]:
tp = 4

### Loading database

In [43]:
data  = pd.read_csv(f'datos/d{tp}.csv')

## Start

avisocuerpo \
avisocargo\
avisorequisitos

Secure datatypes

In [44]:
data['avisocuerpo'] = data['avisocuerpo'].astype(str)
data['avisocargo'] = data['avisocargo'].astype(str)
data['avisorequisitos'] = data['avisorequisitos'].astype(str)

By 'disponibilidadnombre'

In [45]:
data['disponibilidadnombre'].value_counts()

disponibilidadnombre
Jornada Completa                    543178
Mixta (Teletrabajo + Presencial)     81696
Por Turnos                           69668
Teletrabajo                          39730
En terreno                           36644
Part Time                            33957
Práctica                             17352
Práctica Profesional                  6546
Reemplazo                             3930
Media Jornada                         3701
Comisionista                          1845
Free Lance                            1389
Name: count, dtype: int64

In [46]:
data['teletrabajo_'] = data['disponibilidadnombre'] == 'Teletrabajo'

#### Load diccionaries

In [47]:
file_path = "dic.json"

# Open and read the JSON file
with open(file_path, "r", encoding="utf-8") as json_file:
    dic = json.load(json_file)

Let's count

In [48]:
results = pd.read_csv('results.csv', index_col=0)

Bucket 1

In [49]:
data['avcu_b1'] = data['avisocuerpo'].apply(lambda text: any(item in text for item in dic['b1']))
data['avca_b1'] = data['avisocargo'].apply(lambda text: any(item in text for item in dic['b1']))
data['avre_b1'] = data['avisorequisitos'].apply(lambda text: any(item in text for item in dic['b1']))

Bucket 2

In [50]:
data['avcu_b2'] = data['avisocuerpo'].apply(lambda text: any(item in text for item in dic['b2']))
data['avca_b2'] = data['avisocargo'].apply(lambda text: any(item in text for item in dic['b2']))
data['avre_b2'] = data['avisorequisitos'].apply(lambda text: any(item in text for item in dic['b2']))

Bucket 3

In [51]:
data['avcu_b3'] = data['avisocuerpo'].apply(lambda text: any(all(word in text.split() for word in item.split()) for item in dic['b3']))
data['avca_b3'] = data['avisocargo'].apply(lambda text: any(all(word in text.split() for word in item.split()) for item in dic['b3']))
data['avre_b3'] = data['avisorequisitos'].apply(lambda text: any(all(word in text.split() for word in item.split()) for item in dic['b3']))

Bucket 4

In [52]:
data['avcu_b4'] = data['avisocuerpo'].apply(lambda text: any(item in text for item in dic['b4']))
data['avca_b4'] = data['avisocargo'].apply(lambda text: any(item in text for item in dic['b4']))
data['avre_b4'] = data['avisorequisitos'].apply(lambda text: any(item in text for item in dic['b4']))

Saving

In [53]:
results

,avcu_bucket 1,avcu_bucket 2,avcu_bucket 3,avcu_bucket 4,avca_bucket 1,avca_bucket 2,avca_bucket 3,avca_bucket 4,avre_bucket 1,avre_bucket 2,avre_bucket 3,avre_bucket 4,teletrabajo,bucket1,bucket2,bucket3,bucket4,wfh
0,55701,7362,40488,5511,124,1032,188,130,7563,1725,2110,822,47,60657,8719,42008,6281,54246
1,3743,489,3173,191,2,55,9,4,242,47,56,20,37,3883,549,3208,211,3822
2,3722,3290,2933,362,3,419,266,6,260,537,253,49,10671,10732,3870,11972,3204,13732
3,44606,35101,33594,4708,35,6193,3233,24,5791,7731,2789,208,39730,37595,39133,58163,32701,77842

In [54]:
results['avcu_bucket 1'][tp-1] = data['avcu_b1'].sum()
results['avcu_bucket 2'][tp-1] = data['avcu_b2'].sum()
results['avcu_bucket 3'][tp-1] = data['avcu_b3'].sum()
results['avcu_bucket 4'][tp-1] = data['avcu_b4'].sum()

results['avca_bucket 1'][tp-1] = data['avca_b1'].sum()
results['avca_bucket 2'][tp-1] = data['avca_b2'].sum()
results['avca_bucket 3'][tp-1] = data['avca_b3'].sum()
results['avca_bucket 4'][tp-1] = data['avca_b4'].sum()

results['avre_bucket 1'][tp-1] = data['avre_b1'].sum()
results['avre_bucket 2'][tp-1] = data['avre_b2'].sum()
results['avre_bucket 3'][tp-1] = data['avre_b3'].sum()
results['avre_bucket 4'][tp-1] = data['avre_b4'].sum()

results['teletrabajo'][tp-1] = data['teletrabajo_'].sum()

C:\Users\oscarj\AppData\Local\Temp\ipykernel_21772\365356497.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  results['avcu_bucket 1'][tp-1] = data['avcu_b1'].sum()
C:\Users\oscarj\AppData\Local\Temp\ipykernel_21772\365356497.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  results['avcu_bucket 2'][tp-1] = data['avcu_b2'].sum()
C:\Users\oscarj\AppData\Local\Temp\ipykernel_21772\365356497.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  results['avcu_bucket 3'][tp-1] = data['avcu_b3'].sum()
C:\Users\oscarj\AppData\Local\Temp\ipykernel_21772\365356497.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  results['avcu_bucket 4'][tp-1] = data['avcu_b4'].sum()
C:\Users\oscarj\AppData\Local\Temp\ipykernel_21772\365356497.py:6: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  results['avca_bucket 1'][tp-1] = data['avca_b1'].sum()
C:\Users\oscarj\AppData\Local\Temp\ipykernel_21772\365356497.py:7: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  results['avca_bucket 2'][tp-1] = data['avca_b2'].sum()
C:\Users\oscarj\AppData\Local\Temp\ipykernel_21772\365356497.py:8: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  results['avca_bucket 3'][tp-1] = data['avca_b3'].sum()
C:\Users\oscarj\AppData\Local\Temp\ipykernel_21772\365356497.py:9: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  results['avca_bucket 4'][tp-1] = data['avca_b4'].sum()
C:\Users\oscarj\AppData\Local\Temp\ipykernel_21772\365356497.py:11: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  results['avre_bucket 1'][tp-1] = data['avre_b1'].sum()
C:\Users\oscarj\AppData\Local\Temp\ipykernel_21772\365356497.py:12: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  results['avre_bucket 2'][tp-1] = data['avre_b2'].sum()
C:\Users\oscarj\AppData\Local\Temp\ipykernel_21772\365356497.py:13: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  results['avre_bucket 3'][tp-1] = data['avre_b3'].sum()
C:\Users\oscarj\AppData\Local\Temp\ipykernel_21772\365356497.py:14: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  results['avre_bucket 4'][tp-1] = data['avre_b4'].sum()
C:\Users\oscarj\AppData\Local\Temp\ipykernel_21772\365356497.py:16: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  results['teletrabajo'][tp-1] = data['teletrabajo_'].sum()

In [55]:
results

,avcu_bucket 1,avcu_bucket 2,avcu_bucket 3,avcu_bucket 4,avca_bucket 1,avca_bucket 2,avca_bucket 3,avca_bucket 4,avre_bucket 1,avre_bucket 2,avre_bucket 3,avre_bucket 4,teletrabajo,bucket1,bucket2,bucket3,bucket4,wfh
0,55701,7362,40488,5511,124,1032,188,130,7563,1725,2110,822,47,60657,8719,42008,6281,54246
1,3743,489,3173,191,2,55,9,4,242,47,56,20,37,3883,549,3208,211,3822
2,3722,3290,2933,362,3,419,266,6,260,537,253,49,10671,10732,3870,11972,3204,13732
3,44606,35101,33594,4708,35,6193,3233,24,5791,7731,2789,208,39730,37595,39133,58163,32701,77842

In [56]:
print("Sum of avcu_b1:", data['avcu_b1'].sum())
print("Sum of avcu_b2:", data['avcu_b2'].sum())
print("Sum of avcu_b3:", data['avcu_b3'].sum())
print("Sum of avcu_b4:", data['avcu_b4'].sum())

print("Sum of avca_b1:", data['avca_b1'].sum())
print("Sum of avca_b2:", data['avca_b2'].sum())
print("Sum of avca_b3:", data['avca_b3'].sum())
print("Sum of avca_b4:", data['avca_b4'].sum())

print("Sum of avre_b1:", data['avre_b1'].sum())
print("Sum of avre_b2:", data['avre_b2'].sum())
print("Sum of avre_b3:", data['avre_b3'].sum())
print("Sum of avre_b4:", data['avre_b4'].sum())
print('Sum of Teletrabajo:', data['teletrabajo_'].sum())

Sum of avcu_b1: 44606
Sum of avcu_b2: 35101
Sum of avcu_b3: 33594
Sum of avcu_b4: 4708
Sum of avca_b1: 35
Sum of avca_b2: 6193
Sum of avca_b3: 3233
Sum of avca_b4: 24
Sum of avre_b1: 5791
Sum of avre_b2: 7731
Sum of avre_b3: 2789
Sum of avre_b4: 208
Sum of Teletrabajo: 39730

In [57]:
data.to_csv(f'datos/counted/d{tp}_counted.csv')

In [58]:
results.to_csv('results.csv')

In [59]:
results

,avcu_bucket 1,avcu_bucket 2,avcu_bucket 3,avcu_bucket 4,avca_bucket 1,avca_bucket 2,avca_bucket 3,avca_bucket 4,avre_bucket 1,avre_bucket 2,avre_bucket 3,avre_bucket 4,teletrabajo,bucket1,bucket2,bucket3,bucket4,wfh
0,55701,7362,40488,5511,124,1032,188,130,7563,1725,2110,822,47,60657,8719,42008,6281,54246
1,3743,489,3173,191,2,55,9,4,242,47,56,20,37,3883,549,3208,211,3822
2,3722,3290,2933,362,3,419,266,6,260,537,253,49,10671,10732,3870,11972,3204,13732
3,44606,35101,33594,4708,35,6193,3233,24,5791,7731,2789,208,39730,37595,39133,58163,32701,77842