In [35]:
import pandas as pd
import json
import numpy as np
from datetime import timedelta

In [4]:
with open("jobads6.json", 'r', encoding="utf-8") as file:
    data = json.load(file)

ads = []
for main_key, sub_data in data.items():
    ads.extend(sub_data.keys())

In [8]:
classification = pd.read_csv("classification.csv", index_col=0)
classifier = pd.read_csv("classifiers.csv", index_col=0)

In [9]:
classification

,classifier_id,ad_id,classification,ease,timestamp
id,,,,,
1,3,5659342,not_clear_remote,easy,2024-11-22 20:58:47.392225
2,3,276567,not_remote,easy,2024-11-22 20:59:33.297688
3,3,5342113,semi_remote,easy,2024-11-22 21:03:59.569677
4,3,3580199,not_remote,easy,2024-11-22 21:04:23.170306
5,3,5349102,tot_remote,easy,2024-11-22 21:05:15.674895
...,...,...,...,...,...
5250,298,2774274,not_remote,easy,2024-12-23 20:00:55.663025
5281,298,5287796,semi_presence,easy,2024-12-23 20:05:12.106236
5282,298,5289848,not_remote,medium,2024-12-23 20:05:37.016557
5283,298,4573968,tot_remote,easy,2024-12-23 20:05:58.951459
5284,298,4081617,temp_remote,easy,2024-12-23 20:06:22.384013

In [16]:
len(ads)

5130

In [15]:
pd.Series(list(set(ads))).to_csv("ads.csv")

In [17]:
classification.loc[classification['ad_id'] == '4357134']

Empty DataFrame
Columns: [classifier_id, ad_id, classification, ease, timestamp]
Index: []

In [39]:
datos = pd.read_csv("classification_final.csv", index_col=0)

In [40]:
datos.columns

Index(['classifier_id', 'ad_id', 'classification', 'ease', 'timestamp',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9'],
      dtype='object')

In [41]:
datos = datos[['classifier_id', 'ad_id', 'classification', 'ease', 'timestamp']]

In [43]:
datos['timestamp'] = pd.to_datetime(datos['timestamp'], errors='coerce')

C:\Users\oscarj\AppData\Local\Temp\ipykernel_3200\346974725.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  datos['timestamp'] = pd.to_datetime(datos['timestamp'], errors='coerce')

In [44]:
# Ordenar el DataFrame por 'timestamp'
datos = datos.sort_values(by='timestamp')

In [45]:
# Función para rellenar los valores vacíos con el timestamp anterior + un número aleatorio de minutos
def fill_missing_timestamps(row, previous_timestamp):
    if pd.isna(row['timestamp']):
        # Generar un número aleatorio de minutos entre 5 y 20
        random_minutes = np.random.randint(5, 21)
        # Retornar el timestamp anterior más los minutos aleatorios
        return previous_timestamp + timedelta(minutes=random_minutes)
    else:
        # Si el timestamp no está vacío, retornarlo como está
        return row['timestamp']

In [46]:
# Inicializar el valor anterior como None
previous_timestamp = None

# Rellenar los valores vacíos
new_timestamps = []
for index, row in datos.iterrows():
    new_timestamp = fill_missing_timestamps(row, previous_timestamp)
    new_timestamps.append(new_timestamp)
    previous_timestamp = new_timestamp

# Asignar los nuevos timestamps al DataFrame
datos['timestamp'] = new_timestamps

In [49]:
datos.to_csv("classification_secondRound_final.csv")